FROM  pauldmccarthy/fsl-novnc
LABEL org.opencontainers.image.authors="pauldmccarthy@gmail.com"
LABEL org.opencontainers.image.url="https://github.com/pauldmccarthy/rap-novnc-docker-images"
LABEL org.opencontainers.image.documentation="https://github.com/pauldmccarthy/rap-novnc-docker-images"
LABEL org.opencontainers.image.source="https://github.com/pauldmccarthy/rap-novnc-docker-images"
LABEL org.opencontainers.image.title="Ubuntu+noVNC desktop with FSL, Connectome Workbench, and MATLAB installed"
LABEL org.opencontainers.image.description="Ubuntu+noVNC desktop with FSL, Connectome Workbench, and MATLAB installed, for MRI image analysis on the UK Biobank Research Analysis Platform (RAP)."

{% include "emacs.jinja2" %}
{% include "pandora.jinja2" %}
{% include "workbench.jinja2" %}
{% include "msmtemplates.jinja2" %}
{% include "matlab.jinja2" %}
