FROM  ubuntu:24.04
LABEL org.opencontainers.image.authors="pauldmccarthy@gmail.com"
LABEL org.opencontainers.image.url="https://github.com/pauldmccarthy/rap-novnc-docker-images"
LABEL org.opencontainers.image.documentation="https://github.com/pauldmccarthy/rap-novnc-docker-images"
LABEL org.opencontainers.image.source="https://github.com/pauldmccarthy/rap-novnc-docker-images"
LABEL org.opencontainers.image.title="Minimal Ubuntu+noVNC desktop"
LABEL org.opencontainers.image.description="Minimual Ubuntu+noVNC installation for running software within a graphical Linux desktop environment. Includes the DNANexus 'dx' command-line tool for running on the UK Biobank Research Analysis Platform (RAP)."

###############################
# Core utilities + XFCE desktop
###############################

{{ apt_install('locales') }} && \
    locale-gen en_US.UTF-8   && \
    locale-gen en_GB.UTF-8   && \
    update-locale
{{ apt_install(
       'bzip2',
       'curl',
       'dbus-x11',
       'git',
       'libxfce4ui-utils',
       'nano',
       'python3',
       'thunar',
       'tini',
       'tigervnc-common',
       'tigervnc-standalone-server',
       'unzip',
       'xfce4-appfinder',
       'xfce4-panel',
       'xfce4-session',
       'xfce4-settings',
       'xfce4-terminal',
       'xfconf',
       'xfdesktop4',
       'xfwm4',
       'zip') }}
RUN ln -s /usr/bin/python3 /usr/bin/python

#######
# noVNC
#######

RUN NOVNCURL=https://github.com/novnc/noVNC/archive/v1.6.0.tar.gz;         \
    WSCKURL=https://github.com/novnc/websockify/archive/v0.13.0.tar.gz;    \
    mkdir -p /opt/noVNC/utils/websockify                                && \
    cd /opt/noVNC/                                                      && \
    curl -sSfL ${NOVNCURL} | tar -zxf - --strip=1                       && \
    curl -sSfL ${WSCKURL}  | tar -zxf - -C ./utils/websockify --strip=1 && \
    find . -name ".git*"   | xargs rm -rf

RUN mkdir -p         /root/.vnc/
ADD vncserver-config /root/.vnc/config
ADD defaults.json    /opt/noVNC/
ADD startvnc         /opt/noVNC/startvnc
ADD novnc_proxy      /opt/noVNC/utils/novnc_proxy
RUN chmod a+x        /opt/noVNC/startvnc
RUN chmod a+x        /opt/noVNC/utils/novnc_proxy

#################
# micromamba + dx
#################

RUN if   [ $(uname -m) = "x86_64" ]; then                                            \
      MMURL=https://micro.mamba.pm/api/micromamba/linux-64/latest;                   \
    elif [ $(uname -m) = "aarch64" ]; then                                           \
      MMURL=https://micro.mamba.pm/api/micromamba/linux-aarch64/latest;              \
    fi;                                                                              \
    export MAMBA_ROOT_PREFIX=/opt/micromamba;                                        \
    mkdir ${MAMBA_ROOT_PREFIX}                                                    && \
    cd ${MAMBA_ROOT_PREFIX}                                                       && \
    curl -Ls ${MMURL} | tar -xvj bin/micromamba                                   && \
    eval "$(bin/micromamba shell hook -s posix)"                                  && \
    micromamba activate ${MAMBA_ROOT_PREFIX}                                      && \
    bin/micromamba install -y -c conda-forge -p ${MAMBA_ROOT_PREFIX} python=3.12  && \
    bin/micromamba clean --all                                                    && \
    bin/pip install dxpy;

###########################
# XFCE4 panel configuration
###########################

COPY xfce-panel.xml /etc/xdg/xfce4/panel/default.xml

###############
# shell profile
###############

# Base env is activated by default. We also
# always want dx to be on the PATH, so we
# explicitly add /opt/micromamba/bin/.
{{ add_to_profile('export MAMBA_ROOT_PREFIX=/opt/micromamba/') }}
{{ add_to_profile('export PATH=/opt/micromamba/bin/:$PATH') }}
{{ add_to_profile('eval "$(${MAMBA_ROOT_PREFIX}bin/micromamba shell hook -s posix)"') }}
{{ add_to_profile('micromamba activate ${MAMBA_ROOT_PREFIX}') }}

ENV USER=root
WORKDIR /root

ENTRYPOINT [ "/usr/bin/tini", "--", "/opt/noVNC/startvnc" ]