#!/usr/bin/env bash

vncserver :1


# if running on RAP, pre-generate the host name:
if [[ ${DX_JOB_ID} != "" ]]; then
  host="${DX_JOB_ID}.dnanexus.cloud"
  echo ""
  echo "Open this URL in a web browser: https://${host}:8080/vnc.html?host=${host}&port=8080"
  echo ""
  echo "(do not open the second URL listed below)"
  echo ""
fi

/opt/noVNC/utils/novnc_proxy \
  --vnc localhost:5901       \
  --listen 8080
vncserver -kill :1
