name: Build and publish noVNC RAP Docker images

on:
  workflow_dispatch:
    inputs:
      image:
        type:        choice
        required:    true
        description: Image to build (sub-directory name)
        options:
          - ubuntu-novnc
          - fsleyes-novnc
          - workbench-novnc
          - fsl-novnc
          - rap-analysis-novnc
          - all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Thank you https://www.dzombak.com/blog/2024/09/freeing-disk-space-on-github-actions-runners/
      - name: Free disk space
        run:  curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash

      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Checkout LFS files
        run:  git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run:  pip install jinja2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Will start building arm64 at some point in the future
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ubuntu-novnc image
        if:   ${{ github.event.inputs.image == 'all' ||
                  github.event.inputs.image == 'ubuntu-novnc' }}
        run: bash ./build.sh ./ubuntu-novnc --push

      - name: Build fsleyes-novnc image
        if:   ${{ github.event.inputs.image == 'all' ||
                  github.event.inputs.image == 'fsleyes-novnc' }}
        run: bash ./build.sh ./fsleyes-novnc --push

      - name: Build workbench-novnc image
        if:   ${{ github.event.inputs.image == 'all' ||
                  github.event.inputs.image == 'workbench-novnc' }}
        run: bash ./build.sh ./workbench-novnc --push

      - name: Build fsl-novnc image
        if:   ${{ github.event.inputs.image == 'all' ||
                  github.event.inputs.image == 'fsl-novnc' }}
        run: bash ./build.sh ./fsl-novnc --push

      - name: Build RAP analysis image
        if:   ${{ github.event.inputs.image == 'all' ||
                  github.event.inputs.image == 'rap-analysis-novnc' }}
        run: bash ./build.sh ./rap-analysis-novnc --push
