name: Build and publish noVNC RAP Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ubuntu-novnc
        run:  bash ./build.sh ./ubuntu-novnc --push

      - name: Build fsleyes-novnc
        run:  bash ./build.sh ./fsleyes-novnc --push

      - name: Build fsl-novnc
        run:  bash ./build.sh ./fsl-novnc --push
